# Generated by Django 3.2.13 on 2022-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('description', models.TextField(blank=True)),
                ('district', models.CharField(max_length=250, unique=True)),
                ('pediatrician', models.CharField(max_length=250, unique=True)),
                ('urologist', models.CharField(max_length=250, unique=True)),
                ('physician', models.CharField(max_length=250, unique=True)),
                ('gynaecologist', models.CharField(max_length=250, unique=True)),
                ('ent', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
                'ordering': ('branch',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('pname', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250, unique=True)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=250, unique=True)),
                ('address', models.TextField(blank=True)),
                ('diseas', models.TextField(blank=True)),
                ('dname', models.CharField(max_length=250, unique=True)),
                ('appdate', models.DateTimeField()),
                ('bookeddate', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.hospital')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'ordering': ('pname',),
            },
        ),
    ]
