# Generated by Django 3.2.13 on 2022-07-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_hospital_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='branch',
            field=models.TextField(blank=True),
        ),
    ]
