# Generated by Django 3.2.13 on 2022-07-10 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_auto_20220710_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='entimage',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='gynacimage',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='pediaimage',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phyimage',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='uroimage',
        ),
    ]
